#!/bin/sh

set -e

if [ -f /etc/apt/trusted.gpg.d/pl-build-tools.gpg ]; then
    rm -f /etc/apt/trusted.gpg.d/pl-build-tools.gpg
fi

if [ -f /etc/apt/sources.list.d/puppetlabs-build-tools.list ]; then
    rm -f /etc/apt/sources.list.d/puppetlabs-build-tools.list
fi
